Repository capston03/capstone-project-front, pull requests merged in 2022-06, with the labels that each got.

#22 login, signup api 수정 및 업데이트
  lib/login/login.dart
  lib/login/loginEnum.dart
Labels: bug

#27 change main login page (add logo)
  .dart_tool/package_config.json
  .dart_tool/package_config_subset
  android/app/src/main/AndroidManifest.xml
  asset/fonts/VanillaTwilight.otf
  asset/swbLaunch.png
  asset/swb_logo.png
  flutter_launcher_icons.yaml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Info.plist
  lib/login/login.dart
  pubspec.lock
  pubspec.yaml
Labels: develop

#28 Temporal flutter
  .dart_tool/package_config.json
  .dart_tool/package_config_subset
  android/app/src/main/AndroidManifest.xml
  asset/fonts/VanillaTwilight.otf
  asset/swbLaunch.png
  asset/swb_logo.png
  flutter_launcher_icons.yaml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  ios/Runner/Info.plist
  lib/app/data/model/model.dart
  lib/app/data/provider/api.dart
  lib/app/data/provider/callApi.dart
  lib/app/data/repository/stickerMenuRepository.dart
  lib/ar/ar.dart
  lib/ar/stickerMenu.dart
  lib/login/login.dart
  lib/login/signUp.dart
  lib/network/callApi.dart
  lib/profile/profileMain.dart
  lib/profile/profile_pic.dart
  lib/sameArea/newBottomBar.dart
  lib/sticker/stickerUpload.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, develop

#30 Temporal flutter
  lib/app/controller/arController.dart
  lib/ar/ar.dart
  lib/ar/arManager.dart
  lib/ar/stickerMenu.dart
  lib/db/manageSqlflite.dart
  lib/db/thumbnail.dart
  lib/login/login.dart
  lib/map/googlemap.dart
  lib/photo/photoUpload.dart
  lib/profile/profileMain.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement, develop

#32 로그아웃시 기록 삭제
  lib/profile/profileMain.dart
Labels: bug
